// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA64plhFlUkt5ycRe5Q3Q-djwBTDtodRE8',
    appId: '1:1022779474573:web:6be2876c8efc44d5b858c4',
    messagingSenderId: '1022779474573',
    projectId: 'videozup',
    authDomain: 'videozup.firebaseapp.com',
    storageBucket: 'videozup.appspot.com',
    measurementId: 'G-Q153TX4Q2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLyQw4jVFQYEvcJlz4RUQaKQPv9cUK3hY',
    appId: '1:1022779474573:android:3bfc8d67a2919f5ab858c4',
    messagingSenderId: '1022779474573',
    projectId: 'videozup',
    storageBucket: 'videozup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRHCJXXH9WxWliVVRZEP_SqbPAykSEfaE',
    appId: '1:1022779474573:ios:4ee2db7447c16c08b858c4',
    messagingSenderId: '1022779474573',
    projectId: 'videozup',
    storageBucket: 'videozup.appspot.com',
    iosClientId: '1022779474573-j90dnvtfal7sga96tdtdhr7u6luuvb6u.apps.googleusercontent.com',
    iosBundleId: 'com.vidzup.vidzUpload',
  );
}
